/// Flutter icons Icecons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icecons
///      fonts:
///       - asset: fonts/Icecons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Icecons {
  Icecons._();

  static const _kFontFam = 'Icecons';

  static const IconData buddies = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData creditcard_income = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData grid_dynamic_1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bag = const IconData(0xe804, fontFamily: _kFontFam);
}
